image: robertcnelson/debian-bullseye-slim-ti-linux-kernel-dev:latest

build:
  stage: build
  script:
    - . version.sh && echo $BRANCH
    - mkdir -p /root/.cache/ccache/ || true
    - ccache -s
    - tar -xf /mnt/yocto-cache/ccache/ccache-$BRANCH.tar.gz -C / || true
    - ccache -s
    - cp -v system.sh.sample system.sh
    - echo "AUTO_BUILD=1" >> system.sh
    - echo "CORES=12" >> system.sh
    - ./build_deb.sh
    - ccache -s
    - tar -cf ccache-$BRANCH.tar.gz /root/.cache/ccache/
    - cp -v ccache-$BRANCH.tar.gz /mnt/yocto-cache/ccache/ || true
  artifacts:
    paths:
      - "deploy/linux-image-*.deb"

