image: robertcnelson/debian-bullseye-slim-ti-linux-kernel-dev:latest

cache:
  key: "am33x-rt-v6.1"
  paths:
    - dl
    - ccache-am33x-rt-v6.1.tar.gz

build:
  tags:
    - docker-amd64
  stage: build
  script:
    - . version.sh && echo $BRANCH
    - mkdir -p /root/.cache/ccache/ || true
    - ccache -s
    - tar -xf ccache-$BRANCH.tar.gz -C / || true
    - ccache -s
    - cp -v system.sh.sample system.sh
    - echo "AUTO_BUILD=1" >> system.sh
    - echo "LINUX_GIT=/mnt/yocto-cache/git/linux-src/" >> system.sh
    - git config --global --add safe.directory /mnt/yocto-cache/git/linux-src
    - ./build_deb.sh
    - du -sh deploy/linux-image-*.deb || true
    - ccache -s
    - tar -cf ccache-$BRANCH.tar.gz /root/.cache/ccache/
  artifacts:
    expire_in: 5 days
    name: "$CI_PROJECT_NAME-$CI_COMMIT_BRANCH-$CI_JOB_ID"
    paths:
      - "deploy/linux-image-*.deb"

